FROM python:3

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN mkdir /site
# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --shell /bin/bash --disabled-password --gecos "" appuser && chown -R appuser /site
USER appuser


RUN git clone https://github.com/enviroaccounts/site-example.git /site

WORKDIR /site
RUN pip install --no-cache-dir -r .devcontainer/requirements.txt

# Expose port 8050
EXPOSE 8050

# Define an environment variable for the port number
ENV PORT=8050

#ENTRYPOINT [ "python" ]
CMD ["python", "-m", "flask", "--app", "wsgi:application", "run", "--no-debugger", "--no-reload", "--host", "0.0.0.0", "--port", "8050"]
